"""empty message

Revision ID: 1e432e629b0b
Revises: 3c32f4fd1534
Create Date: 2022-08-29 11:31:03.021270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e432e629b0b'
down_revision = '3c32f4fd1534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
