"""empty message

Revision ID: 3c32f4fd1534
Revises: de96b2a44aa5
Create Date: 2022-08-29 11:29:12.590056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c32f4fd1534'
down_revision = 'de96b2a44aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
