"""empty message

Revision ID: c4eafb7e6ef1
Revises: 
Create Date: 2022-08-27 11:48:46.703284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4eafb7e6ef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('error_logs', 'error_code',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='HTTP code error')
    op.alter_column('error_logs', 'error_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               comment='Error text')
    op.alter_column('error_logs', 'error_source',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Path to the file where the error occurred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('error_logs', 'error_source',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment=None,
               existing_comment='Path to the file where the error occurred')
    op.alter_column('error_logs', 'error_description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               comment=None,
               existing_comment='Error text')
    op.alter_column('error_logs', 'error_code',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='HTTP code error')
    # ### end Alembic commands ###
