"""empty message

Revision ID: d7b55b5ac6f1
Revises: 1e432e629b0b
Create Date: 2022-08-29 16:06:46.540397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b55b5ac6f1'
down_revision = '1e432e629b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EquipmentModel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EquipmentModel',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"EquipmentModel_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ModelName', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ModelNumber', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('RusName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('EngName', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
