"""empty message

Revision ID: de07e6232a69
Revises: c4eafb7e6ef1
Create Date: 2022-08-27 12:41:29.067847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de07e6232a69'
down_revision = 'c4eafb7e6ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
