"""empty message

Revision ID: de96b2a44aa5
Revises: a1753219576a
Create Date: 2022-08-29 11:20:54.664505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de96b2a44aa5'
down_revision = 'a1753219576a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
